console.log("test");

function displayWisata(wisata){
    console.log("displayWisata clicked")
    if(wisata == 'danau-maninjau') {
        document.getElementById("section-title").innerHTML = "Danau Maninjau";
        document.getElementById("section-detail").innerHTML = "Danau Maninjau (berarti pemandangan atau peninjauan dalam bahasa Minangkabau) adalah sebuah danau kaldera di kecamatan Tanjung Raya, Kabupaten Agam, provinsi Sumatra Barat, Indonesia. Danau ini terletak sekitar 140 kilometer (87 mi) sebelah utara Kota Padang, ibu kota Sumatra Barat, 36 kilometer (22 mi) dari Bukittinggi, 27 kilometer (17 mi) dari Lubuk Basung, ibu kota Kabupaten Agam. Danau Maninjau memiliki luas 99,5 kilometer persegi (38,4 sq mi), dengan panjang sekitar 16 kilometer (9,9 mi) dan lebar 7 kilometer (4,3 mi). Kedalaman rata-rata adalah 105 meter (344 ft), dengan kedalaman maksimum 165 meter (541 ft). Outlet alami untuk kelebihan air adalah sungai Antokan, yang terletak di sisi barat danau. Ini adalah satu-satunya danau di Sumatera yang memiliki outlet alami ke pantai barat. Sejak tahun 1983, air danau ini telah digunakan untuk menghasilkan Pembangkit Listrik Tenaga Air Maninjau untuk Sumatra Barat, yang dihasilkan sekitar 68 MW pada beban maksimum. Sebagian besar masyarakat yang tinggal di sekitar Danau Maninjau beretnis Minangkabau. Desa-desa di tepi danau antara lain Maninjau dan Bayur. Maninjau adalah tujuan wisata terkenal di wilayah ini karena keindahan pemandangan dan iklimnya yang sejuk. Ini juga merupakan situs untuk paralayang.";
    } else if(wisata == 'ngarai-sianok') {
        document.getElementById("section-title").innerHTML = "Ngarai Sianok"
        document.getElementById("section-detail").innerHTML = "Ngarai Sianok adalah sebuah lembah curam (jurang) yang terletak di perbatasan Kota Bukittinggi, di Kecamatan IV Koto, Kabupaten Agam, Sumatra Barat. Lembah ini memanjang dan berkelok sebagai garis batas kota dari selatan Ngarai Koto Gadang sampai ke nagari Sianok Anam Suku, dan berakhir di Kecamatan Palupuh. Ngarai Sianok memiliki pemandangan yang sangat indah dan juga menjadi salah satu objek wisata andalan provinsi. Ngarai Sianok yang dalam jurangnya sekitar 100 m ini, membentang sepanjang 15 km dengan lebar sekitar 200 m, dan merupakan bagian dari patahan yang memisahkan Pulau Sumatra menjadi dua bagian memanjang (patahan Semangko). Patahan ini membentuk dinding yang curam, bahkan tegak lurus dan membentuk lembah yang hijau—hasil dari gerakan turun kulit bumi (sinklinal)—yang dialiri Batang Sianok (batang berarti sungai, dalam bahasa Minangkabau) yang airnya jernih. Di zaman kolonial Belanda, jurang ini disebut juga sebagai karbouwengat atau kerbau sanget, karena banyaknya kerbau liar yang hidup bebas di dasar ngarai ini. Batang Sianok kini bisa diarungi dengan menggunakan kano dan kayak yang disaranai oleh suatu organisasi olahraga air Qurays. Rute yang ditempuh adalah dari nagari Lambah sampai jorong Sitingkai nagari Palupuh selama kira-kira 3,5 jam. Di tepiannya masih banyak dijumpai tumbuhan langka seperti rafflesia dan tumbuhan obat-obatan. Fauna yang dijumpai misalnya monyet ekor panjang, siamang, simpai, rusa, babi hutan, macan tutul, dan juga tapir.";
    } else if(wisata == 'masjid-batusangkar') {
        document.getElementById("section-title").innerHTML = "Masjid Batusangkar"
        document.getElementById("section-detail").innerHTML = "Masjid Batusangkar adalah salah satu masjid tertua di Indonesia yang terletak di Nagari Rao Rao, Kecamatan Sungai Tarab, Kabupaten Tanah Datar, Sumatra Barat. Masjid berarsitektur perpaduan Minangkabau dan Persia ini mulai dibangun pada tahun 1908 dengan atap berbahan ijuk sebelum akhirnya diganti menjadi seng. Sejak berdirinya, masjid ini sempat mengalami kerusakan yang cukup berarti akibat gempa, seperti pada tahun 1926 dan terakhir 2009. Namun sejak dibangun, masjid ini belum pernah dipugar secara besar-besaran. Renovasi yang pernah dilakukan hanya berupa pelurusan menara yang miring pada tahun 1975 dan penggantian seluruh keramik lama dengan yang baru sekitar tahun 1990-an. Saat ini, selain digunakan untuk aktivitas ibadah umat Islam, masjid satu lantai ini juga digunakan sebagai sarana pendidikan agama. Awalnya, masjid ini juga sempat dijadikan tempat penyusunan strategi perjuangan menghadapi penjajahan Belanda.";
    } else if(wisata == 'muaro') {
        document.getElementById("section-title").innerHTML = "Muaro"
        document.getElementById("section-detail").innerHTML = "Muaro adalah nagari di kecamatan Sijunjung, Kabupaten Sijunjung, Sumatra Barat, Indonesia. Luas Nagari muaro adalah 59,36 kilometer persegi, atau 7,94 persen dari luas wilayahKecamatan Sijunjung.Jarak dari Kantor Wali Nagari ke Ibukota Kecamatan adalah 6,3 kilometer, ke Ibukota Kabupaten adalah 1,8 kilometer, ke Ibukota Provinsi adalah 122 kilometer.Nagari ini masuk dalam daftar 100 desa terbaik menurut Provinsi dan Kabupaten di Indonesia tahun 2018 yang dikeluarkan Kementerian Desa, Pembangunan Daerah Tertinggal dan Transmigrasi.Nagari Muaro terdiri dari 10 (sepuluh) jorong yaitu Tonga. Pamatang Anjur. Pasar Jumat, Batang Salosa, Guguak Dadok, Muara Gambok, Pematang Sari Bulan, Subarang Omak, Pulai Barambai dan Subarang Sukam.";
    } else if(wisata == 'bukit-barisan') {
        document.getElementById("section-title").innerHTML = "Bukit Barisan"
        document.getElementById("section-detail").innerHTML = "Pegunungan Bukit Barisan adalah rangkaian atau jajaran gunung yang membentang sepanjang 1.650 kilometer dari ujung utara (Aceh) sampai ujung selatan (Lampung) di pulau Sumatra. Tercatat ada 40 gunung di Bukit Barisan. Mulai dari Gunung Bandahara di Aceh Tenggara hingga Gunung Tanggamus di Lampung. Rangkaian pegunungan ini mempunyai puncak tertinggi, yaitu Gunung Kerinci yang berlokasi di Jambi dengan ketinggian 3.805 meter di atas permukaan laut. Selain itu, Pegunungan Bukit Barisan terletak dekat pertemuan antara lempeng tektonik Eurasia dan Australia. Disebut Bukit Barisan barangkali karena jajaran pegunungannya sambung-menyambung dan memanjang sejajar di Pulau Sumatra. Adapun disebut ”bukit” dan bukan ”gunung” karena dalam terminologi Melayu lama, kedua nama ini sebenarnya identik. John Crawfurd dalam bukunya, A Descriptive Dictionary of the Indian Islands and Adjacent Countries (1856) menyebutkan bahwa bukit dalam bahasa Melayu sama artinya dengan gunung dalam bahasa Jawa. Kedua istilah ini sering digunakan untuk menunjukkan nama tempat yang tinggi. Sebagai tulang punggung Sumatra, Bukit Barisan berperan penting sebagai sumber air dari semua sungai besar di pulau ini. Sungai-sungai yang bermuara di pantai barat (Samudra Hindia), seperti Alas dan Batangtoru, ataupun yang bermuara di pantai timur (Selat Malaka), seperti Indragiri, Batanghari, dan Musi, berhulu di Bukit Barisan.";
    } else if(wisata == 'jam-gadang') {
        document.getElementById("section-title").innerHTML = "Jam Gadang"
        document.getElementById("section-detail").innerHTML = "Jam Gadang adalah menara jam yang menjadi penanda atau ikon Kota Bukittinggi, Sumatra Barat, Indonesia. Menara jam ini memiliki jam dengan ukuran besar di empat sisinya sehingga dinamakan Jam Gadang, sebutan bahasa Minangkabau yang berarti jam besar. Jam Gadang menjadi lokasi peristiwa penting pada masa sekitar kemerdekaan Indonesia, seperti pengibaran bendera merah putih (1945), Demonstrasi Nasi Bungkus (1950), dan pembunuhan 187 penduduk setempat oleh militer Indonesia atas tuduhan terlibat Pemerintahan Revolusioner Republik Indonesia (1959). Jam Gadang telah dijadikan sebagai objek wisata dengan diperluasnya taman di sekitarnya. Taman tersebut menjadi ruang interaksi masyarakat baik pada hari kerja maupun pada hari libur. Acara-acara yang sifatnya umum biasanya diselenggarakan di sini.";
    } else if(wisata == 'senja-di-padang') {
        document.getElementById("section-title").innerHTML = "Senja di Padang"
        document.getElementById("section-detail").innerHTML = "Sebelum berlibur ke Padang, Anda perlu tahu beberapa tempat untuk melihat senja di 10 tempat wisata Padang. Pemandangan yang ditawarkan sudah pasti akan sangat menakjubkan dan membuat Anda terpesona akan keindahan ciptaan Allah SWT. Bagi Anda yang datang rombongan bisa sewa mobil atau sewa bus di tempat kami. Jadi tak hanya wisata kuliner saja yang maju di Padang, Anda perlu tahu ada banyak destinasi untuk melihat senja di Padang. Hal ini akan menjadi momen yang paling tak terlupakan, terutama bagi Anda yang juga punya hobi fotografi. Setiap tempat yang akan dijelaskan berikut ini memiliki rating yang tinggi dan apa saja itu mari simak berikut ini.";
    } else if(wisata == 'pulau-mentawai') {
        document.getElementById("section-title").innerHTML = "Pulau Mentawai"
        document.getElementById("section-detail").innerHTML = "Kabupaten Kepulauan Mentawai adalah salah satu kabupaten yang terletak di provinsi Sumatra Barat, Indonesia. Kabupaten ini berada di luar pulau Sumatra, terdiri dari empat pulau utama. Kabupaten Kepulauan Mentawai dibentuk berdasarkan UU RI No. 49 Tahun 1999 dan dinamai menurut nama asli geografisnya. Kabupaten ini terdiri dari empat kelompok pulau utama yang berpenghuni yaitu Pulau Siberut, Pulau Sipora, Pulau Pagai Utara, dan Pulau Pagai Selatan yang dihuni oleh mayoritas masyarakat suku Mentawai dan Suku Minangkabau. Selain itu masih ada beberapa pulau kecil lainnya yang berpenghuni namun sebagian besar pulau yang lain hanya ditanami dengan pohon kelapa.";
    }
}

function displayContactUs() {
    document.getElementById("section-title").innerHTML = "Contact Us";
    document.getElementById("section-detail").innerHTML = 'Phone Number: +628XXXXXXXXXX <br><br> Email: wisatasumbar@email.com <br><br> Location: Jl. Mawar No. 1, Jakarta Timur';
}

!function(){"use strict";function r(){function e(){var r={width:u.width/u.naturalWidth,height:u.height/u.naturalHeight},a={width:parseInt(window.getComputedStyle(u,null).getPropertyValue("padding-left"),10),height:parseInt(window.getComputedStyle(u,null).getPropertyValue("padding-top"),10)};i.forEach(function(e,t){var n=0;o[t].coords=e.split(",").map(function(e){var t=1==(n=1-n)?"width":"height";return a[t]+Math.floor(Number(e)*r[t])}).join(",")})}function t(e){return e.coords.replace(/ *, */g,",").replace(/ +/g,",")}function n(){clearTimeout(d),d=setTimeout(e,250)}function r(e){return document.querySelector('img[usemap="'+e+'"]')}var a=this,o=null,i=null,u=null,d=null;"function"!=typeof a._resize?(o=a.getElementsByTagName("area"),i=Array.prototype.map.call(o,t),u=r("#"+a.name)||r(a.name),a._resize=e,u.addEventListener("load",e,!1),window.addEventListener("focus",e,!1),window.addEventListener("resize",n,!1),window.addEventListener("readystatechange",e,!1),document.addEventListener("fullscreenchange",e,!1),u.width===u.naturalWidth&&u.height===u.naturalHeight||e()):a._resize()}function e(){function t(e){e&&(!function(e){if(!e.tagName)throw new TypeError("Object is not a valid DOM element");if("MAP"!==e.tagName.toUpperCase())throw new TypeError("Expected <MAP> tag, found <"+e.tagName+">.")}(e),r.call(e),n.push(e))}var n;return function(e){switch(n=[],typeof e){case"undefined":case"string":Array.prototype.forEach.call(document.querySelectorAll(e||"map"),t);break;case"object":t(e);break;default:throw new TypeError("Unexpected data type ("+typeof e+").")}return n}}"function"==typeof define&&define.amd?define([],e):"object"==typeof module&&"object"==typeof module.exports?module.exports=e():window.imageMapResize=e(),"jQuery"in window&&(window.jQuery.fn.imageMapResize=function(){return this.filter("map").each(r).end()})}();